# This file was generated by GoReleaser. DO NOT EDIT.
cask "ployz" do
  name "ployz"
  desc "Ployz CLI, daemon, and runtime"
  homepage "https://github.com/getployz/ployz"
  version "0.1.0-alpha.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ployz"
  depends_on cask: [
      "docker",
    ],
    formula: [
      "wireguard-tools",
    ]

  on_macos do
    on_intel do
      url "https://github.com/getployz/ployz/releases/download/v#{version}/ployz_#{version}_darwin_amd64.tar.gz"
      sha256 "4ecd379e75e81cb94c9845d5bb78c91e4de1744a46f45f139333eff631fdfc01"
    end
    on_arm do
      url "https://github.com/getployz/ployz/releases/download/v#{version}/ployz_#{version}_darwin_arm64.tar.gz"
      sha256 "0610b66439aa2456248a8b5f652208b1a5e6470ee024ab86aa9bf1063a195fb7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/getployz/ployz/releases/download/v#{version}/ployz_#{version}_linux_amd64.tar.gz"
      sha256 "53329e309caf80d19f57ea98d997c3b59bfd901ef40167b88d0260a8ec60df6c"
    end
    on_arm do
      url "https://github.com/getployz/ployz/releases/download/v#{version}/ployz_#{version}_linux_arm64.tar.gz"
      sha256 "21debe8819d47be11dbaefcd2b3345cb62aa95e97ebe276426e303b1f231c758"
    end
  end

  postflight do
    if OS.mac?
      %w[ployz ployzd ployz-runtime].each do |b|
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/#{b}"]
      end
    end
  end

  # No zap stanza required
end
