# This file was generated by GoReleaser. DO NOT EDIT.
cask "ployz" do
  name "ployz"
  desc "Ployz CLI, daemon, and runtime"
  homepage "https://github.com/getployz/ployz"
  version "0.1.0-alpha.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ployz"
  depends_on cask: [
      "docker",
    ],
    formula: [
      "wireguard-tools",
    ]

  on_macos do
    on_intel do
      url "https://github.com/getployz/ployz/releases/download/v#{version}/ployz_#{version}_darwin_amd64.tar.gz"
      sha256 "fdf19849ccb41fc4fc9e787e27068873d1e343d8d134a0938b49f160c8749398"
    end
    on_arm do
      url "https://github.com/getployz/ployz/releases/download/v#{version}/ployz_#{version}_darwin_arm64.tar.gz"
      sha256 "8037bc1d314087776e071a08afa9493e3d51ad9f02541c85e52ff41fb630c343"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/getployz/ployz/releases/download/v#{version}/ployz_#{version}_linux_amd64.tar.gz"
      sha256 "5f2b0e916eed4b73588ee26c1b65cf3340266cc744b5f9cc4ec78c8a76394e8a"
    end
    on_arm do
      url "https://github.com/getployz/ployz/releases/download/v#{version}/ployz_#{version}_linux_arm64.tar.gz"
      sha256 "2e5b3d9e8c5e71a1de96081735f9edae2ec1c7bf728459ceb9cee53fcdda6e02"
    end
  end

  postflight do
    if OS.mac?
      %w[ployz ployzd ployz-runtime].each do |b|
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/#{b}"]
      end
    end
  end

  # No zap stanza required
end
