# This file was generated by GoReleaser. DO NOT EDIT.
cask "ployz" do
  name "ployz"
  desc "Ployz CLI, daemon, and runtime"
  homepage "https://github.com/getployz/ployz"
  version "0.1.0-alpha.12"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ployz"
  depends_on cask: [
      "docker",
    ],
    formula: [
      "wireguard-tools",
    ]

  on_macos do
    on_intel do
      url "https://github.com/getployz/ployz/releases/download/v#{version}/ployz_#{version}_darwin_amd64.tar.gz"
      sha256 "3f69c5935df1809b25dbf8df275710c8a36a22f826a542b103849174a503d3e9"
    end
    on_arm do
      url "https://github.com/getployz/ployz/releases/download/v#{version}/ployz_#{version}_darwin_arm64.tar.gz"
      sha256 "e89aaac19558c7b975b2a406b0d2b7cab28e848e438805a0853336f104814f95"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/getployz/ployz/releases/download/v#{version}/ployz_#{version}_linux_amd64.tar.gz"
      sha256 "22ecd6725ece99c63bb47afa63a82a29e85fc6dedec4b65785b3b92df3e6bb36"
    end
    on_arm do
      url "https://github.com/getployz/ployz/releases/download/v#{version}/ployz_#{version}_linux_arm64.tar.gz"
      sha256 "f2efa15059286c7e696c1de67b83418f17b3553281e2b81e0fcefb18307d097b"
    end
  end

  postflight do
    if OS.mac?
      %w[ployz ployzd ployz-runtime].each do |b|
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/#{b}"]
      end
    end
  end

  # No zap stanza required
end
