# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ployz < Formula
  desc "Ployz CLI"
  homepage "https://github.com/getployz/ployz2"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/getployz/ployz2/releases/download/v0.1.0/ployz_macos_amd64.tar.gz"
      sha256 "8b0fdc5b8bf1360740f2cd46f848e3f221eca648f03f161b98314cdfae58ffcb"

      def install
        bin.install "ployz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/getployz/ployz2/releases/download/v0.1.0/ployz_macos_arm64.tar.gz"
      sha256 "f227a9523914fbb2a34ce66a7ded69070525b872549eaefde2fc0796561b9827"

      def install
        bin.install "ployz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/getployz/ployz2/releases/download/v0.1.0/ployz_linux_amd64.tar.gz"
        sha256 "345bb4bf3ea29af707f927af28f77bd2642a968be3ce4c203b8fd11196fe7e2a"

        def install
          bin.install "ployz"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/getployz/ployz2/releases/download/v0.1.0/ployz_linux_arm64.tar.gz"
        sha256 "e6160f39a1ec33dce850326c4052f43d799ec49223db2250345f331c8dd0e23f"

        def install
          bin.install "ployz"
        end
      end
    end
  end

  def caveats
    <<~EOS
      This formula replaces the older getployz/ployz implementation as a clean break
      with manual transition, not an in-place compatibility promise.
    EOS
  end
end
